name = Coty 
description = Layout will of full width and will be used for coty project.
preview = preview.png
template = coty-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/coty/coty.layout.css
stylesheets[all][] = css/layouts/coty/coty.layout.no-query.css
